- name: Remove podman containers
  shell: "podman rm -af"
  failed_when: false
  no_log: True
  
- name: Remove podman images
  shell: "podman rmi -a"
  failed_when: false
  no_log: True

- name: Uninstall podman
  dnf:
    name: podman
    state: absent

- name: Remove configs of podman
  file:
    path: /etc/containers
    state: absent

- name: Remove podman registry files
  file:
    path: /u01/volumes/registry
    state: absent
