- name: Uninstall docker
  dnf:
    name: docker-ce
    state: absent

- name: Remove docker files
  file:
    path: /var/lib/docker
    state: absent

# - name: Remove docker for python
#   pip: 
#     name: docker
#     state: absent

# - name: Remove pip
#   dnf:
#     name: python3-pip
#     state: absent

# - name: Remove registry volumes
#   file:
#     path: /u01/volumes/registry
#     state: absent




